### ISSUE TITLE
If decrypt with individual authenticate param, It will be more readable.

### ISSUE THREAD

**Issue by gzx-miller** [appsup-dart/crypto_keys#1]
// encode have authenticate
var v = encrypter.encrypt(new Uint8List.fromList(content.codeUnits),
      additionalAuthenticatedData: new Uint8List.fromList(aad.codeUnits));
  ...
// decode authencate was the child of v, lead a problem, if I need send a encrypt data through network, how can I protect the encrypt data,  and ensure, the receiver can decode it easily?
  var decrypted = decrypter.decrypt(v)

**Comment by rbellens** [comment]
Sorry, don't really understand your question. Can you elaborate a bit on your problem.

**Comment by gzx-miller** [comment]
// Thank you your response, 
// I add one line into the examle code, then it will crash, 
// Event if it havn't crash, I wish the decrypt functon have a param for the authenticate for code-reader.
import 'package:crypto_keys/crypto_keys.dart';
import 'dart:typed_data';
main() {
  // Generate a new random symmetric key pair
  var keyPair = new KeyPair.generateSymmetric(128);

  // Use the public key to create an encrypter with the AES/GCM algorithm
  var encrypter =
      keyPair.publicKey.createEncrypter(algorithms.encryption.aes.gcm);

  // Encrypt the content with an additional authentication data for integrity
  // protection
  var content = "A very secret text";
  var aad = "It is me";
  var v = encrypter.encrypt(new Uint8List.fromList(content.codeUnits),
      additionalAuthenticatedData: new Uint8List.fromList(aad.codeUnits));

  print("Encrypting '$content'");
  print("Ciphertext: ${v.data}");
  print("Authentication tag: ${v.authenticationTag}");

  // Use the private key to create the decrypter
  var decrypter =
      keyPair.privateKey.createEncrypter(algorithms.encryption.aes.gcm);

// If I sent the encrypted data and the autenticationTag through network, 
// then I receive it, conbinate to a new 'Encryptionresult';
var newEncryptedData = EncryptionResult(v.data, authenticationTag: v.authenticationTag);

  // Decrypt and verify authentication tag
  var decrypted = decrypter.decrypt(newEncryptedData);

  print("Decrypted text: '${new String.fromCharCodes(decrypted)}'");
}

**Comment by rbellens** [comment]
you need to copy the entire encryption result, including initialization vector and aad:

      var newEncryptedData = EncryptionResult(v.data,
        authenticationTag: v.authenticationTag,
        additionalAuthenticatedData: v.additionalAuthenticatedData,
        initializationVector: v.initializationVector);

But indeed, the error message is not very descriptive.

**Comment by gzx-miller** [comment]
OK, this code will run normally, but too many parameters need to send by network, I find it too complicated.

**Comment by rbellens** [comment]
It depends on the algorithm you use which data has to be sent. AES/GCM actually combines encryption and signing (this means the additional authenticated data is not encrypted, but you can verify that it has not been changed between sender and receiver). Other algorithms like AES/CBC do not have this authentication part and so no need for the authentication tag and aad. 

If you want a simple way to serialize/deserialize this for sending it over a network, you could have a look at JSON Web Encryption (JWE), which defines a format for encrypted data. Check out this package: https://github.com/appsup-dart/jose
