### ISSUE TITLE
Unable to use `ES256K` algorithm

### ISSUE THREAD

**Issue by muhammadsaddamnur** [appsup-dart/crypto_keys#12]
I was trying to implement JOSE/JWT using `ES256K` algorithm using (jose)[https://pub.dev/packages/jose], which listed as supported signing algo JWS on it's README. But, turns out it did not work and give me error that algo is not supported. I tried to dig out on the source code and found that the algo is not listed on the library and also in this library that listed as it's dependency.

I've created this [(PR)](https://github.com/appsup-dart/crypto_keys/pull/11) that works for me right now, Please kindly review!

Thank you!

**Comment by rbellens** [comment]
Thank you for your PR! It has now been merged.
