### ISSUE TITLE
RSAES OAEP support

### ISSUE THREAD

**Issue by jeroentrappers** [appsup-dart/crypto_keys#2]
Hi, 

First of all: thanks a lot for this library! I'm trying to implement OpenID connect with Itsme (Belgian mobile id)  through it (and the jose plugin)

Is there a reason RSAES OAEP is not implemented?

It seems that if I change the code (algorithms.dart, line 92) from 
`
  final oaep = new AlgorithmIdentifier._(
      "enc/RSA/ECB/OAEPWithSHA-1AndMGF1Padding",
      () => throw new UnimplementedError("RSA OAEP mode not implemented"));`
to
`
  final oaep = new AlgorithmIdentifier._(
      "enc/RSA/ECB/OAEPWithSHA-1AndMGF1Padding",
      () => new pc.OAEPEncoding(new pc.RSAEngine()));`
it will work.
Itsme seems to be using this for JWT - JWS - JWE encryption.

kind regards,

Jeroen

**Comment by rbellens** [comment]
Hi @jeroentrappers,

Thanks for pointing this out. It seems to work indeed. Not sure anymore what was the reason. Maybe it wasn't yet supported by pointycastle at the time.
I've added it now.
