### ISSUE TITLE
pointycastle update

### ISSUE THREAD

**Issue by vixez** [appsup-dart/crypto_keys#8]
Hello,

There is a [bug](https://github.com/bcgit/pc-dart/issues/112) in `pointycastle` 3.0.0, which has been solved in 3.2.0
Could this package be updated to 3.2.0, so I don't need to manually override `pointycastle: ^3.2.0`?

Thanks

**Comment by rbellens** [comment]
This package already supports the latest version of `pointycastle`. No need to use `dependency_overrides`. Simply, make sure you have the latest versions of all dependencies by running `dart pub upgrade`.
