### ISSUE TITLE
example of using algorithms.encrypting_aes_cbc

### ISSUE THREAD

**Issue by bkhezry** [appsup-dart/crypto_keys#9]
Hi,
I could not find an example of using `algorithms.encrypting_aes_cbc` encryption in the test and readme file.
could you please help me?

**Comment by rbellens** [comment]
`algorithms.encrypting_aes_cbc` is the same as `algorithms.encrypting.aes.cbc`. It is recommended to use the latter. The former will be deprecated. There are some examples in the `crypt_keys_test.dart` file or you can check out the `encryption_example.dart` and replace the `algorithms.encryption.aes.gcm` with `algorithms.encryption.aes.cbc`.
